name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chandrakanthm/hello-world-fastapi:latest_v1.0
    - name: Push the Docker image 
      run: docker login -u chandrakanthm -p ${{ secrets.DOCKERHUB_TOKEN }} && docker push chandrkanthm/hello-world-fastapi:latest_v1.0
